export const GET_ITEM="GET_ITEM";
export const UPDATE_ITEM="UPDATE_ITEM";
export const DELETE_ITEM="DELETE_ITEM";
export const ADD_ITEM="ADD_ITEM";

export const GET_CUSTOMER="GET_CUSTOMER";
export const UPDATE_CUSTOMER="UPDATE_CUSTOMER";
export const DELETE_CUSTOMER="DELETE_CUSTOMER";
export const ADD_CUSTOMER="ADD_CUSTOMER";


export const DELETE_DEBITCUR="DELETE_DEBITCUR";
export const GET_AINVOICE="GET_AINVOICE";

export const GET_DEBIT="GET_DEBIT";
export const UPDATE_DEBIT="UPDATE_DEBIT";
export const DELETE_DEBIT="DELETE_DEBIT";
export const ADD_DEBIT="ADD_DEBIT";



export const GET_DEBITDES="GET_DEBITDES";
export const UPDATE_DEBITDES="UPDATE_DEBITDES";
export const DELETE_DEBITDES="DELETE_DEBITDES";
export const ADD_DEBITDES="ADD_DEBITDES";


export const GET_RECEIPT="GET_RECEIPT";
export const UPDATE_RECEIPT="UPDATE_RECEIPT";
export const DELETE_RECEIPT="DELETE_RECEIPT";
export const ADD_RECEIPT="ADD_RECEIPT";

export const GET_INVOICE="GET_INVOICE";
export const UPDATE_INVOICE="UPDATE_INVOICE";
export const DELETE_INVOICE="DELETE_INVOICE";
export const ADD_INVOICE="ADD_INVOICE";

export const GET_PROPAC="GET_PROPAC";
export const UPDATE_PROPAC="UPDATE_PROPAC";
export const DELETE_PROPAC="DELETE_PROPAC";
export const ADD_PROPAC="ADD_PROPAC";

export const GET_INVOICEDESC="GET_INVOICEDESC";
export const UPDATE_INVOICEDESC="UPDATE_INVOICEDESC";
export const DELETE_INVOICEDESC="DELETE_INVOICEDESC";
export const ADD_INVOICEDESC="ADD_INVOICEDESC";

export const UPDATE_PROGRAM="UPDATE_PROGRAM";
export const DELETE_PROGRAM="DELETE_PROGRAM";
export const ADD_PROGRAM="ADD_PROGRAM";
export const GET_PROGRAM="GET_PROGRAM";

export const UPDATE_PACKAGE="UPDATE_PACKAGE";
export const DELETE_PACKAGE="DELETE_PACKAGE";
export const ADD_PACKAGE="ADD_PACKAGE";
export const GET_PACKAGE="GET_PACKAGE";

export const UPDATE_OWNER="UPDATE_OWNER";
export const DELETE_OWNER="DELETE_OWNER";
export const ADD_OWNER="ADD_OWNER";
export const GET_OWNER="GET_OWNER";


export const UPDATE_SERVICE="UPDATE_SERVICE";
export const DELETE_SERVICE="DELETE_SERVICE";
export const ADD_SERVICE="ADD_SERVICE";
export const GET_SERVICE="GET_SERVICE";

export const LOADING='LOADING';
export const GET_ERROR='GET_ERROR';
export const CLEAR_ERROR='CLEAR_ERROR';
export const UPP_INVOICEDESC='UPP_INVOICEDESC';
export const DELETE_UPDATEIN='DELETE_UPDATEIN';

export const USER_LOADING='USER_LOADING';
export const USER_LODED='USER_LODED';
export const LOGIN_SUCCESS='LOGIN_SUCCESS';
export const REGISTER_SUCCESS='REGISTER_SUCCESS';
export const LOGOUT_SUCCESS='LOGOUT_SUCCESS';
export const LOGIN_FAIL='LOGIN_FAIL';
export const REGISTER_FAIL='REGISTER_FAIL';
export const AUTH_ERROR='AUTH_ERROR';
export const UPDATE_USER='UPDATE_USER';


export const DELETE_USER="DELETE_USER";
export const ADD_USER="ADD_USER";
export const GET_USER="GET_USER";
